server:
    port: 8888
spring:
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                     searchLocations: file:///C:/Users/LAB203-xx/Desktop/SOPLap/Config/src/main/resources/config/microservice